gestorUser/urls.py
from django.urls import path

from gestorUser.views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    ]

inventarioVeterinariaNA/urls.py
from django.contrib import admin
from django.urls import path, include
from inventarioVeterinariaNA.views import index
from gestorUser.views import listaUsuarios, editarUsuarios
from gestorProductos.views import listadoProductos, listadoCategorias ,registroProductos, registroCategorias, editarCategoria, editarProducto, eliminarCategoria, eliminarProducto


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")), # Todas las urls de autenticación
    path("usuarios/", include("gestorUser.urls")),
    path("", index, name="home"),
    #Vistas Usuarios
    path('listaUsuarios/', listaUsuarios, name='lista_usuarios'),
    path('editarUsuarios/<int:id>/', editarUsuarios, name='editar_usuarios'),
    #Vistas Productos y Categorias
    path('productos/', listadoProductos, name='productosData'),
    path('categorias/', listadoCategorias, name='categoriasData'),
    path('nuevoProducto/', registroProductos, name='productoRegistro'),
    path('nuevaCategoria/', registroCategorias, name='categoriaRegistro'),
    path('eliminarProducto/<int:id>', eliminarProducto, name='eliminarProductos'),
    path('eliminarCategoria//<int:id>', eliminarCategoria, name='eliminarCategorias'),
    path('editarProducto/<int:id>', editarProducto, name='editarProducto'),
    path('editarCategoria/<int:id>', editarCategoria, name='editarCategoria'),
]

gestorUser/models.py
from django.db import models

# Create your models here.

gestorUser/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistroUsuarioForm(UserCreationForm):
    username = forms.CharField()
    email = forms.EmailField()
    password1 = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    username.widget.attrs['class'] = 'form-control'
    username.widget.attrs['placeholder'] = 'Nombre de usuario'
    username.widget.attrs['autocomplete'] = 'username'
    email.widget.attrs['class'] = 'form-control'
    email.widget.attrs['placeholder'] = 'Correo electrónico'
    email.widget.attrs['autocomplete'] = 'email'
    password1.widget.attrs['class'] = 'form-control'
    password1.widget.attrs['placeholder'] = 'Contraseña'
    password1.widget.attrs['autocomplete'] = 'new-password'
    password2.widget.attrs['class'] = 'form-control'
    password2.widget.attrs['placeholder'] = 'Repetir Contraseña'
    password2.widget.attrs['autocomplete'] = 'new-password'

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    


class FormularioEditarUsuario(forms.ModelForm):
    nueva_contraseña = forms.CharField(widget=forms.PasswordInput, required=False, label="Nueva Contraseña")
    confirmar_contraseña = forms.CharField(widget=forms.PasswordInput, required=False, label="Confirmar Contraseña")

    class Meta:
        model = User
        fields = ['username','email']

    def limpiarDatos(self):
        limpiar = super().clean()
        contraseña = limpiar.get("Nueva Contraseña")
        confirmar_contraseña = limpiar.get("Confirmar Contraseña")

        if contraseña and contraseña != confirmar_contraseña:
            raise forms.ValidationError("Las contraseñas no coinciden")
        return limpiar

gestorUser/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from rest_framework.reverse import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.models import User
from django.contrib import messages
from gestorUser.forms import FormularioEditarUsuario, RegistroUsuarioForm





# Vista para la creación de usuarios.
class SignUpView(SuccessMessageMixin, CreateView):
    form_class = RegistroUsuarioForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"
    success_message = "¡Usuario creado exitosamente!"


#Vista para ver el listado de usuarios
def listaUsuarios(request):
    users = User.objects.all()
    data = {'users':users}
    return render(request, 'gestorUser/lista_usuarios.html', data)

#Vista para la modificación de perfiles de usuarios
def editarUsuarios(request, id):
    user = User.objects.get(id=id)
    if request.method == 'POST':
        form = FormularioEditarUsuario(request.POST, instance=user)
        if form.is_valid():
            user = form.save(commit=False)
            nueva_contraseña = form.cleaned_data.get('nueva_contraseña')
            if nueva_contraseña:
                user.set_password(nueva_contraseña)
            user.save()
            messages.success(request, 'Usuario actualizado con éxito')
            return redirect('login')
    else:
        form = FormularioEditarUsuario(instance=user)
    return render(request, 'gestorUser/editar_usuarios.html', {'form':form})

templates/gestorUser/editar_usuarios.html
{% extends "base/base.html" %}

{% load static %}

{% block titulo %}
Editar Perfil
{% endblock %}


{% block contenido %}

<h1 class="h3 my-5 text-gray-800 text-center">Editar Perfil</h1>

<div class="container">
    <form class="user" method="post">
        {% csrf_token %}

        <!-- Mensajes de exito o error -->
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show mt-3" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}

        <!-- Nombre de usuario -->
        <div class="form-group mt-5">
            <label for="id_username" class="form-label my-2">Nombre de usuario:</label>
            <input type="text" class="form-control form-control-user" id="id_username"
                name="{{ form.username.html_name }}" autocomplete="username"
                value="{{ form.username.value|default_if_none:'' }}" placeholder="Nombre de Usuario">
            <!-- Mostrar error de validación para este campo -->
            {% if form.username.errors %}
            <div class="alert alert-danger mt-2" role="alert">
                {{ form.username.errors.0 }}
            </div>
            {% endif %}
        </div>

        <!-- Correo electronico -->
        <div class="form-group">
            <label for="id_email" class="form-label my-2">Correo electrónico:</label>
            <input type="email" class="form-control form-control-user" id="id_email" name="{{ form.email.html_name }}"
                value="{{ form.email.value|default_if_none:'' }}" placeholder="Correo Electrónico">
            <!-- Mostrar error de validacion -->
            {% if form.email.errors %}
            <div class="alert alert-danger mt-2" role="alert">
                {{ form.email.errors.0 }}
            </div>
            {% endif %}
        </div>

        <!-- Nueva contraseña -->
        <div class="form-group">
            <label for="id_nueva_contraseña" class="form-label my-2">Nueva contraseña:</label>
            <input type="password" class="form-control form-control-user" id="id_nueva_contraseña"
                name="{{ form.nueva_contraseña.html_name }}" placeholder="Nueva Contraseña">
            <!-- Mostrar error de validacion -->
            {% if form.nueva_contraseña.errors %}
            <div class="alert alert-danger mt-2" role="alert">
                {{ form.nueva_contraseña.errors.0 }}
            </div>
            {% endif %}
        </div>

        <!-- Confirmar contraseña -->
        <div class="form-group">
            <label for="id_confirmar_contraseña" class="form-label my-2">Confirmar contraseña:</label>
            <input type="password" class="form-control form-control-user" id="id_confirmar_contraseña"
                name="{{ form.confirmar_contraseña.html_name }}" placeholder="Confirmar Contraseña">
            <!-- Mostrar error de validacion -->
            {% if form.confirmar_contraseña.errors %}
            <div class="alert alert-danger mt-2" role="alert">
                {{ form.confirmar_contraseña.errors.0 }}
            </div>
            {% endif %}
        </div>

        <button type="submit" class="btn btn-primary btn-user btn-block mt-5">
            Guardar cambios
        </button>
        <a href="{% url 'home' %}" class="btn btn-danger btn-user btn-block my-2">
            Volver a la Página Principal
        </a>
    </form>
</div>

{% endblock %}

templates/gestorUser/lista_usuarios.html
{% extends "base/base.html" %}

{% load static %}

{% block titulo %}
Editar Perfil
{% endblock %}


{% block contenido %}

<!-- CSS DataTable -->
<link rel="stylesheet" href="https://cdn.datatables.net/2.1.8/css/dataTables.bootstrap5.css">

<h1 class="h3 my-5 text-gray-800 text-center">Listado de usuarios</h1>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="h5 m-0 font-weight-bold text-success">Usuarios</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="example" width="100%" cellspacing="0">
                <thead class="table-dark">
                    <tr>
                        <th>ID</th>
                        <th>Usuario</th>
                        <th>Correo</th>
                        <th>Fecha de creación</th>
                        <th>Última conexión </th>
                    </tr>
                </thead>
                <tbody>
                    {% if users %}
                    {% for user in users %}
                    <tr>
                        <th scope="row">{{user.id}}</th>
                        <td>{{user.username}}</td>
                        <td>{{user.email}}</td>
                        <td>{{user.date_joined}}</td>
                        <td>{{user.last_login}}</td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                        <td colspan="9" class="text-center">No hay productos registrados</td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>


<!-- JS DataTable -->
<script src="https://code.jquery.com/jquery-3.7.1.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/2.1.8/js/dataTables.js"></script>
<script src="https://cdn.datatables.net/2.1.8/js/dataTables.bootstrap5.js"></script>
<script>
    var table = new DataTable('#example', {
    language: {
        url: '//cdn.datatables.net/plug-ins/2.1.8/i18n/es-MX.json',
    },
});
</script>

{% endblock %}